server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: custmomer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: fd-service
          uri: lb://fixed-deposit-service
          predicates:
            - Path=/fixeddeposit/**
      enabled: true
      discovery:
        locator:
          enabled: true





eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/my-discovery-server/eureka
  #    register-with-eureka: true
  #    fetch-registry: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1000

#

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
