#server.port=9000
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false


server:
  port: 8761
  servlet:
    context-path: /my-discovery-server
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
